hello:
    pattern: /
    defaults: { _controller: AcmeMobileBundle:Main:index}

about:
    pattern: /about
    defaults: { _controller: AcmeMobileBundle:Main:about}

delivery:
    pattern: /delivery
    defaults: { _controller: AcmeMobileBundle:Main:delivery}

faq:
    pattern: /faq
    defaults: { _controller: AcmeMobileBundle:Main:faq}
    
contact:
    pattern: /contact
    defaults: { _controller: AcmeMobileBundle:Main:contact}

category:
    pattern: /category/{catId}/{page}/{results}
    defaults: { _controller: AcmeMobileBundle:Main:category, page:p1,results:6}
    requirements: 
        catId: \d+
        page: p\d+

car:
    pattern: /car/{carId}
    defaults: { _controller: AcmeMobileBundle:Main:car}
    requirements:
        carId: \d+

featured:
    pattern: /featured
    defaults: { _controller: AcmeMobileBundle:Main:getFeaturedCar}

search:
    pattern: /search/{page}/{results}
    defaults: { _controller: AcmeMobileBundle:Main:getFilteredCar, page:p1, results:6}
    requirements:
        page: p\d+

refresh:
    pattern: /refresh
    defaults: { _controller: AcmeMobileBundle:Main:refresh}
